import { Location } from './location';

export let LOCATIONS: Location[] = [
  {
    id: 0,
    name: "Abbey Bank",
    pin: "pin.png",
    rank: 88,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunset",
    image: "abbey-bank.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/howden-reservoir-upper-derwent-valley/\">James Pictures</a>",
    content: "Abbey Bank is situated on the Eastern flanks of Derwent Reservoir and has a excellent vantage overlooking Howden Dam. Best shot in Autumn at Sunset. <br/>It’s a good hours walk from <a href=\"https://www.peakdistrict.gov.uk/visiting/visitor-centres/derwent\">Fairholmes Visitors Center</a> so leave plenty of time to get into position, and remember it’s a Pay & Display.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.421003,
    lng: -1.7457297,
    osgrid: "SK 169 916"
  },
  {
    id: 1,
    name: "Axe Edge",
    pin: "pin.png",
    rank: 99,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunrise",
    image: "axe-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The best photo to take from Axe Edge is looking North East down the Dove Valley towards Chrome Hill. Best shot with a Telephoto lens at Sunrise, hopefully with a little bit of mist! Check out <a href=\"https://jackierobinsonphotography.com/peak-district\">Jackie Robinson</a>, she has some fantastic compressed shots from Axe Edge.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.226149,
    lng: -1.9523547,
    osgrid: "SK 032 699"
  },
  {
    id: 2,
    name: "Back Forest",
    pin: "pin.png",
    rank: 68,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "back-forest.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/back-forest-and-beyond/\">James Pictures</a>",
    content: "Back Forest woodland is below Lower Roach End and gives is a perfect foreground for a great view over to Shutlingsloe. Best shot at Sunset, and there is an abundance of stunning purple heather most years - this is roadside location so very accessible.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.177555,
    lng: -2.0050707,
    osgrid: "SJ 997 644"
  },
  {
    id: 3,
    name: "Back Tor",
    pin: "pin.png",
    rank: 83,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunset",
    image: "back-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Many people love walking the Great Ridge which divides the Hope and Edale Valleys, voted many times as one of the best walks in the country it is also loved by photographers! It’s a good 2 mile walk (45 mins) to get to Back Tor from <a href=\"https://goo.gl/maps/ZtCc7KeC5mC2\">Mam Nick Car Park</a> but the views from the surrounding areas are stunning. I particularly like the view looking South at Sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.360314,
    lng: -1.7868047,
    osgrid: "SK 142 848"
  },
  {
    id: 4,
    name: "Bamford Edge",
    pin: "pin.png",
    rank: 28,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "bamford-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Bamford Edge was one of the first photography locations I visited with its stunning views overlooking Ladybower Reservoir and its overhanging gritstones it’s a perfect sunset location looking over to Win Hill. It’s about a 30 minute walk in from a layby on New Road.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3608737,
    lng: -1.689781,
    osgrid: "SK 207 849"
  },
  {
    id: 5,
    name: "Baslow Edge",
    pin: "pin.png",
    rank: 36,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "baslow-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/sunset-at-bamford-edge/\">James Pictures</a>",
    content: "Baslow Edge is on the southern side of Curbar Gap and is a nice alternative location to Curbar and Froggatt Edge’s. Access and parking are easy, and within a short 10 minute walk you can admire views of the Derwent Valley overlooking Baslow and Calver villages. A popular shot is of the <a href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/the-anvil-stone/\">Anvil Stone</a> at Sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.261074,
    lng: -1.6129033,
    osgrid: "SK 259 738"
  },
  {
    id: 6,
    name: "Beresford Dale",
    pin: "pin.png",
    rank: 77,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "beresford-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Hidden away between the village of Hartington and Wolfscote Dale is the idyllic Beresford Dale. It’s a limestone dale following the flow of the River Dove and is a great location to visit at Autumn to get some of the fabulous autumnal colours reflecting in the river.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.124519,
    lng: -1.8127117,
    osgrid: "SK 126 586"
  },
  {
    id: 7,
    name: "Blake Mere",
    pin: "pin.png",
    rank: 72,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunset",
    image: "blake-mere.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Blake Mere up on Morridge Moor above Leek is a roadside location and has a commanding view over Ramshaw Rocks and The Roaches. Best shot at sunset its hard not to get a nice photograph from this location.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1486191,
    lng: -1.9440972,
    osgrid: "SK 038 612"
  },
  {
    id: 8,
    name: "Bolehill Quarry",
    pin: "pin.png",
    rank: 57,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "bolehill-quarry.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Bolehill Quarry is such a stunning place to visit, I can spend many an hour wandering though the silver birch trees looking for compositions. The best time to visit is at sunrise and if you can visit when the mist and fog is low enough you will get some magical surreal images of the trees. Park at <a href=\"https://goo.gl/maps/D2Mtxb3uT96uADXe6\">Surprise View Car Park</a> and then walk the short 10 minutes.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3137824,
    lng: -1.6286313,
    osgrid: "SK 248 797"
  },
  {
    id: 9,
    name: "Bunster Hill",
    pin: "pin.png",
    rank: 63,
    difficulty: 4,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "bunster-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Lung Buster Hill as I like to call it! I’ve given this a 4-star difficulty rating simply because it’s hard to access carrying all your camera kit, the easiest way to access is from Ilam Village then head North towards Ilamtops Farm and then turn East and contour around. If you’re like me, you park near the Izaak Walton Hotel and proceed straight up the side... not advisable! Best time to photograph is at Sunrise looking over to Thorpe Cloud.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.0572583,
    lng: -1.8047619,
    osgrid: "SK 131 511"
  },
  {
    id: 10,
    name: "Burbage Rocks",
    pin: "pin.png",
    rank: 52,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "burbage-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Burbage Rocks are situated in the North East of Derbyshire Peak. The best views can be admired from the path looking South West over Burbage Moor and Carl Walk. Best time to shoot this location is when the heather is in flower at Sunset. You can park at Burbage Bridge and walk along the Eastern path.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3409082,
    lng: -1.6124145,
    osgrid: "SK 259 827"
  },
  {
    id: 11,
    name: "Butterton",
    pin: "pin.png",
    rank: 54,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "butterton.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/st-bartholomew-church-in-butterton/\">James Pictures</a>",
    content: "Butterton is a small village in the Staffordshire Peak which overlooks the Manifold Valley rich in history from the Manifold Light Railway and Ecton mine. The Church of St Bartholomew's has provided me with many images of its spire rising from the mist, there are also a few old barns on the outskirts that make for good foreground interest.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.109595,
    lng: -1.9068857,
    osgrid: "SK 063 569"
  },
  {
    id: 12,
    name: "Carhead Rocks",
    pin: "pin.png",
    rank: 53,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "carhead-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/carhead-rocks/\">James Pictures</a>",
    content: "Carhead Rocks is down below Stanage Edge. I’ve only been once. You can photography the Knuckle Stone whilst admiring open views across to Hathersage and beyond. It’s very easy to get to and has parking within 400 meters. Best shot at Sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.341103,
    lng: -1.6409562,
    osgrid: "SK 240 827"
  },
  {
    id: 13,
    name: "Cave Dale",
    pin: "pin.png",
    rank: 21,
    difficulty: 2,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "cave-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/peveril-castle-2/\">James Pictures</a>",
    content: "Cave Dale is very easily accessible from the village of Castleton. However, both limestone sides are extremely steep so to get a good vantage point you need to walk a mile up the path. You can then turn around and admire the view of Peveril Castle and Hope Valley. Best photographed at Sunrise and even better photographed in a temperature inversion.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3387531,
    lng: -1.7799032,
    osgrid: "SK 147 824"
  },
  {
    id: 14,
    name: "Chatsworth",
    pin: "pin.png",
    rank: 92,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "chatsworth.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Chatsworth is Chatsworth, I’ve been once in 5 years to photograph it. I feel its far to manicured to be classed as a landscape and more of an addition to a location guide for novelty purposes. Great if you want to photograph deer and sheep. Best photographed in the midday but only if you are trying to pass time of day.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.2275433,
    lng: -1.6136161,
    osgrid: "SK 258 701"
  },
  {
    id: 15,
    name: "Chrome Hill",
    pin: "red-pin.png",
    rank: 2,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunrise",
    image: "chrome-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/walker-on-chrome-hill/\">James Pictures</a>",
    content: "The infamous Dragons Back of the Upper Dove Valley in Derbyshire! I have lost count of the times and angles I have photographed this limestone reef knoll. Chrome Hill is best photographed from the lower slopes at sunrise, if you <a href=\"#chrome-hill\">read more</a> I can go into more detail of best places to park and approach from.",
    readmore: "block",
    readmoreurl: "#chrome-hill",
    county: "Derbyshire",
    lat: 53.2027282,
    lng: -1.9141696,
    osgrid: "SK 058 672"
  },
  {
    id: 16,
    name: "Crow Stones Edge",
    pin: "pin.png",
    rank: 55,
    difficulty: 5,
    season: "Autumn",
    bestTime: "Sunset",
    image: "crow-stones-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "One of the most remote photography locations I have visited in the Peak. High up above Howden Reservoir on the Moorland is Crow Stones Edge, comprising of The Crow Stones and The Hanging Stone. Mid-Week you can park at Howden Reservoir and walk up in an hour or so. Weekends it’s a 3 hour hike from Langsett Reservoir. Hard work but worth it. The route we took is <a target=\"_blank\" rel=\"noopener\" href=\"https://drive.google.com/open?id=1aw_yQjCGwTERS6GO8zHNd0K4dNM-7PUw&usp=sharing\">here</a>",
    readmore: "none",
    readmoreurl: "",
    county: "South Yorkshire",
    lat: 53.46849823,
    lng: -1.74340691,
    osgrid: "SK 171 967"
  },
  {
    id: 17,
    name: "Crowdicote",
    pin: "pin.png",
    rank: 69,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunrise",
    image: "crowdicote.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Situated on the county boundaries of Derbyshire and Staffordshire, Crowdicote is a lovely rural village (with a nice pub too). The county boundary is the River Dove and is prone to temperature inversions at sunrise. Best photographed up above Crowdicote on the Derbyshire side, roadside or there is a public footpath higher up. I’ve always shot at Sunrise with low lying mist in the valley.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.1820932,
    lng: -1.8582427,
    osgrid: "SK 095 650"
  },
  {
    id: 18,
    name: "Curbar Edge",
    pin: "red-pin.png",
    rank: 6,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "curbar-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/curbar-edge-sunrise/\">James Pictures</a>",
    content: "A very easy to get to location and perfect if you’re in short time. It’s a quick 10 minutes’ walk from the carpark to prime shooting location. The most common vantage is looking South along the Derwent valley to Chatsworth Estate. Defiantly best shot at Sunrise as it takes an additional 10-20 minutes for the sun to rise over the horizon over Birchen Edge.",
    readmore: "block",
    readmoreurl: "#curbar-edge",
    county: "Derbyshire",
    lat: 53.2704355,
    lng: -1.6112868,
    osgrid: "SK 260 748"
  },
  {
    id: 19,
    name: "Dove Valley",
    pin: "pin.png",
    rank: 51,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "dove-valley.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/upper-dove-valley-2/\">James Pictures</a>",
    content: "The Dove Valley runs from Dovedale to Axe Edge Moor following the River Dove. I have added this as a location because the Dove Valley is so photogenic, but probably encompasses several other beautiful locations. The best places to admire The Dove Valley are from the flanks around Hartington and Hitter Hill.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.142596,
    lng: -1.8133057,
    osgrid: "SK 125 606"
  },
  {
    id: 20,
    name: "Dovedale",
    pin: "pin.png",
    rank: 58,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "dovedale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/lovely-reflections-from-thorpe-cloud/\">James Pictures</a>",
    content: "The River Dove has carved its way through Dovedale creating a place we have all come to love and admire. Great for a family picnic, or a walk along to Lovers Leap! I prefer to head higher up to admire the views. Some of the Northern vantage points are not easily accessible and will require you to park at Thorpe and contour around the Northern side. Allow a good hour to walk in - The views are worth it though.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.0666659,
    lng: -1.792088,
    osgrid: "SK 140 521"
  },
  {
    id: 21,
    name: "Dean Rocks",
    pin: "red-pin.png",
    rank: 8,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunset",
    image: "dean-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The North West Peak has some of the most rugged and remote landscape in the Peak and up above Dovestones Reservoir is in my opinion a breath of fresh air! If you want to get away from everything then this is the place, stunning landscapes. Sunset is best, my only regret is not being able to get to these locations more often.",
    readmore: "block",
    readmoreurl: "#dean-rocks",
    county: "Greater Manchester",
    lat: 53.5301681,
    lng: -1.9668187,
    osgrid: "SE 022 037"
  },
  {
    id: 22,
    name: "Dowel Dale",
    pin: "pin.png",
    rank: 70,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunrise",
    image: "dowel-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A tricky place to photography is Dowel Dale, North of Chrome Hill. Parking is somewhat none existent so leave plenty of time to get into location. Best shot at Sunrise which makes this location one of the more remote places to shoot from.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.2102,
    lng: -1.89167457,
    osgrid: "SK 073 681"
  },
  {
    id: 23,
    name: "Doxey Pool",
    pin: "pin.png",
    rank: 64,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunset",
    image: "doxey-pool.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/doxey-pool/\">James Pictures</a>",
    content: "Located up on the top of The Roaches, Doxey Pool is a small pool of water. Next to the pool are the gritstone edges looking South towards Hen Cloud and in the right conditions can look fantastic. Can be shot at either Sunrise or Sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1626828,
    lng: -1.997923,
    osgrid: "SK 002 628"
  },
  {
    id: 24,
    name: "Drabber Tor",
    pin: "pin.png",
    rank: 24,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "drabber-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/wolfscote-dale-peak-district/\">James Pictures</a>",
    content: "Drabber Tor is in Wolfscote Dale, my favourite dale for its remoteness! Its also very popular with climbers. A limestone rock formation which if shot from the right vantage point can catch the light nice at Sunrise. Best to park in Alstonefield and walk in which takes about 40 minutes.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.109225,
    lng: -1.7923767,
    osgrid: "SK 139 569"
  },
  {
    id: 25,
    name: "Earl Sterndale",
    pin: "pin.png",
    rank: 59,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunrise",
    image: "earl-sterndale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Up above Earl Sterndale is a limestone pavement that looks out over towards Parkhouse and Chrome Hills. It’s a good 30 minute walk from Earl Sterndale, a little tricky to photography but if you get the right conditions works very well.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.207151,
    lng: -1.8694957,
    osgrid: "SK 088 677"
  },
  {
    id: 26,
    name: "Ecton Hill",
    pin: "pin.png",
    rank: 30,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunrise",
    image: "ecton-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Ecton Hill is one of the larger hills in the White Peak and doesn’t really hold many great views from the Triangular Pillar. I was somewhat disappointed when I reached the top. However, the best views can be had approx 1 kilometre south, still on Ecton Hill but on the Southern sides along the Manfold Trial. It took me a long time to explore Ecton Hill, and the southern & eastern banks are defiantly more photogenic.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.106078,
    lng: -1.8548494,
    osgrid: "SK 098 565"
  },
  {
    id: 27,
    name: "Froggatt Edge",
    pin: "pin.png",
    rank: 32,
    difficulty: 2,
    season: "Winter",
    bestTime: "Sunrise",
    image: "froggatt-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Froggatt Edge is past Curbar Edge along the Derwent Valley, both locations can be photographed at the same time and is best photographed at sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.280147,
    lng: -1.6313131,
    osgrid: "SK 246 759"
  },
  {
    id: 28,
    name: "Gib Torr",
    pin: "pin.png",
    rank: 97,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "gib-torr.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Gib Torr is a dark gritstone formation North of The Roaches and is maintained by Staffordshire Wildlife Trust. It’s a tricky location to photograph and is best photographed when the heather is in bloom.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.2133205,
    lng: -1.9554613,
    osgrid: "SK 030 684"
  },
  {
    id: 29,
    name: "Goyt Valley",
    pin: "pin.png",
    rank: 66,
    difficulty: 1,
    season: "Spring",
    bestTime: "Midday",
    image: "goyt-valley.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Goyt Valley is vast and a very interesting area to walk and explore, check out the <a href=\"https://goyt-valley.org.uk/\">Goyt Valley website</a>! I actually find it one of the hardest places to photograph and have spent many hours exploring every nook and cranny from a landscape perspective. There is a lovely <a href=\"https://goyt-valley.org.uk/the-packhorse-bridge/\">packhourse bridge</a> over the River Goyt which was moved in 1965.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.256351,
    lng: -1.983476,
    osgrid: "SK 012 732"
  },
  {
    id: 30,
    name: "Gratton Hill",
    pin: "pin.png",
    rank: 61,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunrise",
    image: "gratton-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Gratton Hill sits between Narrowdale & Wolfscote Dale and has some grand views North to Derbyshire and West to Staffordshire. I often go here for sunrise and then walk down into Wolfscote Dale. Parking is not so easy and why I’ve given it 3 stars difficulty. Getting up here for sunrise requires an early start allowing an hour walk in.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.110846,
    lng: -1.8062567,
    osgrid: "SK 130 570"
  },
  {
    id: 31,
    name: "Grindon Moor",
    pin: "pin.png",
    rank: 94,
    difficulty: 1,
    season: "Spring",
    bestTime: "Sunrise",
    image: "grindon-moor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Grindon Moor is open moorland in Staffordshire Peak, it has excellent views over the Manifold Valley and villages of Butterton and Grindon. There is a very photogenic sycamore tree on the skyline that can be shot from the roadside - best at sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.093503,
    lng: -1.8978702,
    osgrid: "SK 069 551"
  },
  {
    id: 32,
    name: "Hall Dale",
    pin: "pin.png",
    rank: 100,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "hall-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Hall Dale is the North West entrance to Dove Dale. You can park at the small hamlet of Stanshope and walk 20 minutes East. It’s a short and sharp climb up the side of the valley to get the best views, best shot an hour before sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.082154,
    lng: -1.8029022,
    osgrid: "SK 133 538"
  },
  {
    id: 33,
    name: "Hanging Stone",
    pin: "pin.png",
    rank: 85,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "hanging-stone.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A 20 minute walk from Roach End brings you to the Hanging Stone on Back Forest Ridge - it has some great views over the Staffordshire Moorlands and I’ve often spent many an hour watching the weather and light change from this vantage point.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.184531,
    lng: -2.0214369,
    osgrid: "SJ 986 652"
  },
  {
    id: 34,
    name: "Hartington",
    pin: "pin.png",
    rank: 67,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "hartington.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "I wouldn’t normally include a village in a landscape directory, but I often stop for a brew on my travels and many of the villages in the Peak. I find one of the most photogenic views is this taken above Hartington, looking over to St. Giles' Church.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.139632,
    lng: -1.8097167,
    osgrid: "SK 128 602"
  },
  {
    id: 35,
    name: "Hen Cloud",
    pin: "pin.png",
    rank: 45,
    difficulty: 2,
    season: "Autumn",
    bestTime: "Sunset",
    image: "hen-cloud.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "I first climbed Hen Cloud as a small boy. I recall lying down and looking over the edge in awe of the views. You can see for miles from Hen Cloud, but it’s not photographed that much - photographers prefer to go to the five clouds side and shoot from above Don Whillans Hut. Best shot at sunset, loads of parking but it can get very busy in the school holidays.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.157716,
    lng: -1.9929284,
    osgrid: "SK 005 622"
  },
  {
    id: 36,
    name: "Higger Tor",
    pin: "pin.png",
    rank: 17,
    difficulty: 1,
    season: "Winter",
    bestTime: "Sunrise",
    image: "higger-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/higger-tor/\">James Pictures</a>",
    content: "I always feel Higger Tor a bit of a cop out location. One of those locations that is a last minute dash because your running late as its within 5 minutes of the roadside it’s very easy to access. It’s a location that is popular for photography workshops too as it has lots of foreground rock formations and expansive views down the Derwent Valley. Best shot at sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.333809,
    lng: -1.617754,
    osgrid: "SK 256 819"
  },
  {
    id: 37,
    name: "High Wheeldon",
    pin: "pin.png",
    rank: 31,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "high-wheeldon.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Great for views of the Dove Valley looking West. Its rather flat to the rear looking into Derbyshire, but the best view can be had looking North to Parkhouse & Chrome hills. Great for wide angle and telephoto use. Best shot at sunrise as the sun will rise behind you casting some fantastic shadows over the valley.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.1909982,
    lng: -1.8692996,
    osgrid: "SK 088 659"
  },
  {
    id: 38,
    name: "Hitter Hill",
    pin: "red-pin.png",
    rank: 10,
    difficulty: 1,
    season: "Winter",
    bestTime: "Sunrise",
    image: "hitter-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "It took me a while to find Hitter Hill. After exploring the Upper Dove Valley, it was probably the last place left to visit and I wish I’d visited it sooner! This location got me a <a href=\"https://www.take-a-view.co.uk/2016-award-winners/\">Highly Commended</a> shot in Landscape Photographer of the Year 2016. It’s great for both sunrise and sunset and is a short 15 minute walk from Earl Sterndale Village.",
    readmore: "block",
    readmoreurl: "#hitter-hill",
    county: "Derbyshire",
    lat: 53.198253,
    lng: -1.8741377,
    osgrid: "SK 085 668"
  },
  {
    id: 39,
    name: "Ilam",
    pin: "pin.png",
    rank: 95,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "ilam.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The cottages of Ilam are said to represent a Switzerland alpine feel with its beautiful cross and manicured gardens it’s hard not to stop and admire. I’ve photographed this area from all vantage points. I often find the best place to shoot is from the flanks of Bunster Hill - but its hard work getting up the hill. You could explore Ilam Park or the stunning Church of The Holy Cross which dates to the Saxons era.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.0538526,
    lng: -1.8051354,
    osgrid: "SK 131 507"
  },
  {
    id: 40,
    name: "Ladybower Reservoir",
    pin: "pin.png",
    rank: 78,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "ladybower-reservoir.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The famous plug holes! I shot them back in 2012. I have only revisited once since to show a friend where they are. It’s one of those sights that you must see and hear, and of course photograph! Parking is within a 5 minute walk I find the overflow closest to the road better to photograph.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3662552,
    lng: -1.6999577,
    osgrid: "SK 200 855"
  },
  {
    id: 41,
    name: "Lathkill Dale",
    pin: "pin.png",
    rank: 42,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "lathkill-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A quite dale between Monyash and Bakewell. Many photo opportunities from the flanks but Parsons Tor is the best. I have shot it only once before because some dedication is required to get to location on time for sunrise. Parking is available at the <a href=\"https://goo.gl/maps/DXKrj4KNLUasoNZr7\">Monyash</a> end of the dale but its then a 45 minute walk into location. Defiantly best shot at sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.190621,
    lng: -1.7481361,
    osgrid: "SK 169 659"
  },
  {
    id: 42,
    name: "Lathkill Dale Tufa Weir",
    pin: "pin.png",
    rank: 86,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Midday",
    image: "lathkill-dale-tufa-weir.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "South of Parsons Tor flows the River Lathkill, but only at certain times of the year as the river flows underground in summer months. I have visited this location many times to find no water. It’s a good walk in from either Monyash or Over Haddon and is classed as one of the hidden gems of the Peak District.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.1873601,
    lng: -1.737395,
    osgrid: "SK 176 656"
  },
  {
    id: 43,
    name: "Mam Tor",
    pin: "red-pin.png",
    rank: 1,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "mam-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/mam-tor-gates/\">James Pictures</a>",
    content: "Mam Tor needs no introduction, it is the most photographed location in the Peak District with the famous gates taking prime location! It has been said that the queue can be 10 deep waiting to get \"that shot\" of those gates on a busy morning. Of course, there are many other vantage spots along the Great Ridge and it’s hard to not come away with a good photograph.",
    readmore: "block",
    readmoreurl: "#mam-tor",
    county: "Derbyshire",
    lat: 53.349098,
    lng: -1.8118419,
    osgrid: "SK 126 835"
  },
  {
    id: 44,
    name: "Manifold Valley",
    pin: "red-pin.png",
    rank: 7,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "manifold-valley.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/manifold-valley-and-thors-cave/\">James Pictures</a>",
    content: "The stunning Manifold Valley or Manifold Way in Staffordshire is 8 miles of stunning scenery. The most popular vantages are Thors Cave and Wetton Hill. I prefer the latter looking down the valley to Thors Cave, especially on a misty morning. Plenty of parking in the valley, but if you want to admire views from Wetton Hill leave a good 40 minutes to park and walk in before sunrise.",
    readmore: "block",
    readmoreurl: "#manifold-valley",
    county: "Staffordshire",
    lat: 53.1071,
    lng: -1.85257,
    osgrid: "SK 099 566"
  },
  {
    id: 45,
    name: "Millstone Edge",
    pin: "pin.png",
    rank: 56,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "millstone-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Millstone Edge, situated between Surprise View and Over Owler Tor is an old disused millstone quarry and has some lovely rock faces which face the setting sun. Best shot at sunset when the heather is in bloom. Be aware it is an easily accessible location so large numbers of photographers visit when the heather is in flower. Parking is via Surprise View Car Park and is a short 5 minute walk.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.320393,
    lng: -1.6314047,
    osgrid: "SK 246 804"
  },
  {
    id: 46,
    name: "Milldale",
    pin: "pin.png",
    rank: 89,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "milldale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Milldale is a quaint village in the Staffordshire Peak, the best view can be had from the Derbyshire side looking back over Viator's Bridge. Probably best shot before Spring or Autumn so you can see the houses through the trees. Parking is easy as there is a Pay and Display at the village.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.0894052,
    lng: -1.7948623,
    osgrid: "SK 138 547"
  },
  {
    id: 47,
    name: "Monsal Dale",
    pin: "pin.png",
    rank: 46,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "monsal-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Monsale Dale has some nice views of the Headstone Viaduct from the top near the hotel, so you can shoot this location from the road if you wish, or wander down into the dale to have a look around. Best shot at sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.240594,
    lng: -1.726758,
    osgrid: "SK 185 715"
  },
  {
    id: 48,
    name: "Monsal Head Tunnel",
    pin: "pin.png",
    rank: 93,
    difficulty: 2,
    season: "Any",
    bestTime: "Midday",
    image: "monsal-head-tunnel.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Great for some abstract or long exposure practice, the tunnels on the Monsal Trail can be photographed at all times of the day. Parking is at Monsal Head and it’s a short 20 minute walk to the tunnels.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.246717,
    lng: -1.742536,
    osgrid: "SK 172 724"
  },
  {
    id: 49,
    name: "Morridge Moor",
    pin: "pin.png",
    rank: 84,
    difficulty: 1,
    season: "Winter",
    bestTime: "Sunset",
    image: "morridge-moor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Morridge Moor is open barren landscape up above Leek, Staffordshire. It can be a harsh place often windy and wet. However, it also makes for some fantastic abstract work, lone trees, windswept trees and untouched areas defining the landscape. An interesting location that under the right conditions are unique.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.150771,
    lng: -1.9444397,
    osgrid: "SK 038 615"
  },
  {
    id: 50,
    name: "Narrowdale",
    pin: "pin.png",
    rank: 87,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunrise",
    image: "narrowdale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Narrowdale is a small dale of Wolfscote Dale that has some fantastic old outbuildings and unspoilt views. Best shot at sunrise, as the valleys behind are very prone to mist. Parking is not so easy, so plan ahead if you want to get here early.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1155749,
    lng: -1.8172696,
    osgrid: "SK 123 576"
  },
  {
    id: 51,
    name: "Narrowdale Hill",
    pin: "pin.png",
    rank: 47,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunrise",
    image: "narrowdale-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Narrowdale Hill isn’t easy to get to and why I’ve marked it 3 stars for difficulty. You can try parking in Alstonefield village or Beresford Dale but it’s a good 45 minutes’ walk to location then. If it’s a misty morning, Narrowdale & The Dove Valley is prone to mist you can get excellent views looking north along the Dove Valley.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.111902,
    lng: -1.8180297,
    osgrid: "SK 122 572"
  },
  {
    id: 52,
    name: "Over Owler Tor",
    pin: "pin.png",
    rank: 38,
    difficulty: 2,
    season: "Autumn",
    bestTime: "Sunset",
    image: "over-owler-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A quick 20 minute walk from Surprise View Car Park this location is a popular one. Best shot when the heather is in bloom at sunset. You could do a few locations at once from here to be fair. Surprise View, Bolehill Quarry, Millstone Edge and Lawrencefield. If your feeling energetic you could also do Padley Gorge.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.32285,
    lng: -1.6271767,
    osgrid: "SK 249 807"
  },
  {
    id: 53,
    name: "Padley Gorge",
    pin: "pin.png",
    rank: 43,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Midday",
    image: "padley-gorge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Padley Gorge is stunning, it is even more stunning at Autumn… a small gorge following Burbage Brook through an ancient forest, what more could you ask for. Plenty of parking roadside - you can shoot this location at midday after a sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.315781,
    lng: -1.6164267,
    osgrid: "SK 256 799"
  },
  {
    id: 54,
    name: "Parkhouse Hill",
    pin: "red-pin.png",
    rank: 5,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunset",
    image: "parkhouse-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The smaller of the 2 hills in the Upper Dove Valley. The larger being Chrome Hill. I have shot from the summit at both Sunrise & Sunset and had excellent worthy results as the light casts great shadows across the land and hillsides. Parking is from Earl Sterndale and a brisk 30 minute walk. The hill can get very slippy in the wet as the limestone reveals its self, take your time going back down.",
    readmore: "block",
    readmoreurl: "#parkhouse-hill",
    county: "Derbyshire",
    lat: 53.1989498,
    lng: -1.8841301,
    osgrid: "SK 078 668"
  },
  {
    id: 55,
    name: "Peaseland Rocks",
    pin: "pin.png",
    rank: 33,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunrise",
    image: "peaseland-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Located above Wolfscote Dale this limestone rock formation is as dramatic as Winnats Pass in my opinion and far less visited, which is now I like it! Walk in from Alstonefield takes a good 30 minutes and take your time on the edge as its steep and slippery with nothing to protect your fall.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.109266,
    lng: -1.7929847,
    osgrid: "SK 139 569"
  },
  {
    id: 56,
    name: "Ramshaw Rocks",
    pin: "pin.png",
    rank: 14,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "ramshaw-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A great location for a last minute dash, it is a roadside location and best shot an hour before sunset. You could combine this location with Roach End Barn once the sun has dropped behind the Roaches.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1538049,
    lng: -1.976167,
    osgrid: "SK 016 618"
  },
  {
    id: 57,
    name: "Ravens Tor",
    pin: "pin.png",
    rank: 75,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunset",
    image: "ravens-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "You don’t see many photos from Ravens Tor. It’s a lovely vantage looking South down Dove Dale. A brisk 30 minute walk in from Stanshope village and a steep climb onto Stanshope Pasture. I’m yet to get a nice shot from here personally. Best shot an hour before Sunset, and probably at Autumn. I think if shot in the summer the green vegetation would not reveal the limestone rock formations of Ilam Rock or Pickering Tor.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.081649,
    lng: -1.7915627,
    osgrid: "SK 140 538"
  },
  {
    id: 58,
    name: "Ringing Roger",
    pin: "pin.png",
    rank: 19,
    difficulty: 4,
    season: "Any",
    bestTime: "Sunrise",
    image: "ringing-roger.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/ringing-roger-sunrise/\">James Pictures</a>",
    content: "Park at Edale Pay and Display and start the hour or so walk up to Ringing Roger for sunrise. Yes, it’s much dedication needed for this location and you will most defiantly need a torch. I would recommend going up in the day to get your bearings before trying it at sunrise. Once on location you have stunning views of Edale Valley. I’ve always shot at sunrise, but I have seen just as good images at sunset. I’d probably make the day of the climb and stay up on Kinder for the day.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3815796,
    lng: -1.8152588,
    osgrid: "SK 123 872"
  },
  {
    id: 59,
    name: "Roach End Barn",
    pin: "pin.png",
    rank: 40,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "roach-end-barn.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/roach-end-barn-in-staffordshire/\">James Pictures</a>",
    content: "There are several old barns at the North Western end of The Roaches called Roachend Farm but commonly referred to as Roach End Barn, as photographers have favoured the last larger barn that is still has its roof intact. The barns are a short walk over the field and are great for sunset. I wrote a little blog some years ago about <a href=\"https://www.jamespictures.co.uk/blog/roach-end-barn/\">Roach End Barn</a>.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.175779,
    lng: -2.0081891,
    osgrid: "SJ 995 642"
  },
  {
    id: 60,
    name: "Roystone Grange",
    pin: "pin.png",
    rank: 25,
    difficulty: 4,
    season: "Autumn",
    bestTime: "Sunset",
    image: "roystone-grange.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Roystone Grange is probably one of the less known photography locations in the Peak, in fact I’ve only to this day seen a handful of photographers shoot this location. Parking is via <a href=\"https://goo.gl/maps/QMqULGfAQV7oT1DHA\">Minninglow Car Park</a> and then a 2 mile walk along the High Peak Trail through Roystone Grange Farm and Pumphouse. You have arrived. Study the area and grab a vantage.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.106312,
    lng: -1.7043078,
    osgrid: "SK 198 566"
  },
  {
    id: 61,
    name: "Roystone Rocks",
    pin: "pin.png",
    rank: 35,
    difficulty: 4,
    season: "Any",
    bestTime: "Sunset",
    image: "roystone-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/roystone-rocks-peak-district/\">James Pictures</a>",
    content: "Roystone Rocks is another less photographed location with its stunning unique rock formations and untouched landscape it’s like being in another part of the country. A good hours walk into location from <a href=\"https://goo.gl/maps/QMqULGfAQV7oT1DHA\">Minninglow Car Park</a>. Leave enough time to explore the area as well as its unique.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.107778,
    lng: -1.7092492,
    osgrid: "SK 195 567"
  },
  {
    id: 62,
    name: "Salt Cellar",
    pin: "red-pin.png",
    rank: 9,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunset",
    image: "salt-cellar.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Up on top of Derwent Edge is the Salt Cellar. A popular photographed millstone grit rock formation that is unique to the area. Best shot at sunset. Parking is via <a href=\"https://goo.gl/maps/EvecDUf1u5FtV9Db7\">Heatherdene Car Park</a> and then a good hours walk up around the back of Ladybower Inn and up onto the edge. You will pass many a nice viewpoint to admire views across Ladybower Reservoir.",
    readmore: "block",
    readmoreurl: "#salt-cellar",
    county: "Derbyshire",
    lat: 53.3999992,
    lng: -1.7157547,
    osgrid: "SK 189 892"
  },
  {
    id: 63,
    name: "Sheen Hill",
    pin: "pin.png",
    rank: 76,
    difficulty: 2,
    season: "Any",
    bestTime: "Midday",
    image: "sheen-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "One of the first locations I visited in the Peak was Sheen Hill, from a far it seems to have great views but once you get to the summit it is somewhat disappointing and flat. Its about the only summit that sits above the inversions of the Dove Valley in the Staffordshire Peak. Parking is close by and there is a public footpath to the summit.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.159893,
    lng: -1.8379878,
    osgrid: "SK 109 625"
  },
  {
    id: 64,
    name: "Shining Tor",
    pin: "pin.png",
    rank: 23,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunset",
    image: "shining-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/shining-tor/\">James Pictures</a>",
    content: "The highest point in Cheshire is that of Shining Tor it’s also the seventh highest in the Peak and gives great views out over the Cheshire plains. You can access the path up to Shining Tor from a layby just North of the Cat and Fiddle Inn on the A537 or from <a href=\"https://goo.gl/maps/YtaYsBYnwSR3qJRA8\">Pym Chair Car Park</a>. The latter is then a relatively flat walk in via Cats Tor and takes about 40 minutes. Best time to shoot is sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Cheshire",
    lat: 53.260654099999996,
    lng: -2.018255,
    osgrid: "SJ 988 737"
  },
  {
    id: 65,
    name: "Shutlingsloe",
    pin: "pin.png",
    rank: 12,
    difficulty: 3,
    season: "Winter",
    bestTime: "Sunrise",
    image: "shutlingsloe.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/shutlingsloe-sunrise/\">James Pictures</a>",
    content: "Shutlingsloe, considered the Matterhorn of Cheshire with its commanding views of Cheshire is a must visit at sunrise. It’s a 40 minute walk in from <a href=\"https://goo.gl/maps/RgZ5u3rcqUUgL3ef6\">Standing Stone Car Park</a> and has some of the best views for miles. You could try parking at <a href=\"https://goo.gl/maps/XRwDASMoU2ivyWSh8\">Clough House</a> as well, but whilst its a shorter route its uphill all the way!",
    readmore: "none",
    readmoreurl: "",
    county: "Cheshire",
    lat: 53.2358043,
    lng: -2.0405393,
    osgrid: "SJ 973 709"
  },
  {
    id: 66,
    name: "Stanage Edge",
    pin: "pin.png",
    rank: 16,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunset",
    image: "stanage-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/stanage-edge-millstones/\">James Pictures</a>",
    content: "An easily accessible gritsone edge that has great views. Parking is roadside and you can be on the edge within 10 minutes of parking. Best shot at sunset and late afternoon as the sun lights up the face of the rock.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3472902,
    lng: -1.6507706,
    osgrid: "SK 233 834"
  },
  {
    id: 67,
    name: "Stepping Stones",
    pin: "pin.png",
    rank: 73,
    difficulty: 1,
    season: "Spring",
    bestTime: "Midday",
    image: "stepping-stones.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "I remember visiting the stepping stones as kid many moons ago, such an iconic family location now visited by many year on year. It can get very busy over the summer holidays, so I have always shot them at late afternoon once the crowds have gone. Seems easier and the light can cast some great shadows onto Thorpe Cloud. I try to avoid parking in the £3 Pay and Display as you can park on the main Thorpe Road for free.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.056495,
    lng: -1.7799776,
    osgrid: "SK 148 510"
  },
  {
    id: 68,
    name: "Surprise View",
    pin: "pin.png",
    rank: 39,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunset",
    image: "surprise-view.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/surprise-view-at-night/\">James Pictures</a>",
    content: "Great for a view over Heathersage and Edale towards Mam Tor. Threre is a composition roadside on the sharp right hand bend where you can practice some light trails as the cars go past.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.316148,
    lng: -1.6306167,
    osgrid: "SK 247 799"
  },
  {
    id: 69,
    name: "Swainsley Tunnel",
    pin: "pin.png",
    rank: 98,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "swainsley-tunnel.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Swainsley Tunnel is part of the disused Leek and Manifold Valley Light Railway and is located between Ecton and Wetton Mill. The tunnel is 150 meters in length and now forms part of the Manifold Way and is easily accessible.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1160499,
    lng: -1.867876,
    osgrid: "SK 089 576"
  },
  {
    id: 70,
    name: "The Roaches",
    pin: "red-pin.png",
    rank: 3,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "the-roaches.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/heather-on-the-roaches/\">James Pictures</a>",
    content: "A gritstone rocky ridge near Leek which overlooks Tittesworth Reservoir and the Staffordshire Moorlands. Very accessible with parking nearby. It’s a short 20 minute walk up on top - all uphill by the way! But defiantly worth it. The Roaches can get very busy in the day so I would defiantly recommend shooting sunrise or sunset. I prefer shooting sunrise from the southern end and sunset from the northern end.",
    readmore: "block",
    readmoreurl: "#roaches",
    county: "Staffordshire",
    lat: 53.156109,
    lng: -1.995237,
    osgrid: "SK 005 622"
  },
  {
    id: 71,
    name: "Thorpe Cloud",
    pin: "pin.png",
    rank: 27,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "thorpe-cloud.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Above the Dove Dale stepping stones is a flat top hill called Thorpe Cloud, it is very popular with walkers visiting the dale to get a nice vantage looking down Dovedale. It’s also said to be able to view the extraordinary solar phenomenon <a href=\"https://en.wikipedia.org/wiki/Double sunset\">double sunset</a> of Thorpe Cloud from the nearby Lin Dale (between Thorpe Cloud and Thorpe Pastures) on summer solstice.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.0563621,
    lng: -1.7840552,
    osgrid: "SK 145 510"
  },
  {
    id: 72,
    name: "Thorpe Pastures",
    pin: "pin.png",
    rank: 74,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "thorpe-pastures.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/thorpe-pastures/\">James Pictures</a>",
    content: "Thorpe Pasture lie to the North of the village of Thorpe. They raise up onto high ground to the West of the village of Tissington and give some nice views of the old ridge and furrow fields from times gone by. Best shot either side of sunrise & sunset to get the side light and shadows over the fields.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.066924,
    lng: -1.7617967,
    osgrid: "SK 160 522"
  },
  {
    id: 73,
    name: "Thors Cave",
    pin: "pin.png",
    rank: 13,
    difficulty: 2,
    season: "Autumn",
    bestTime: "Sunrise",
    image: "thors-cave.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/thors-cave-manifold-valley/\">James Pictures</a>",
    content: "Thors Cave in the Manifold Valley – You can climb to the top and shoot back along the valley, but I prefer shooting North up the valley towards the cave. I’ve explored both sides of the valley and both are equally as good. It takes a good 30 minutes after sunrise for the sun to hit the entrance of the cave, so don’t worry if your running a little late. Best shot at sunrise. Parking is via a <ahref=\" https://goo.gl/maps/X5NJsoTrZTeNLqvv9\">small layby on Leek Road</a>, or plenty of parking by Wetton Mill.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.092772,
    lng: -1.8574609,
    osgrid: "SK 096 550"
  },
  {
    id: 74,
    name: "Three Shires Head",
    pin: "pin.png",
    rank: 48,
    difficulty: 2,
    season: "Any",
    bestTime: "Midday",
    image: "three-shires-head.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/three-shires-head/\">James Pictures</a>",
    content: "Three Shires Head sits on the county border of Staffordshire, Derbyshire and Cheshire and has 2 packhorse bridges and a few pannier pools from times gone by. Its 1.5 miles walk in and the path is rocky so wear good ankle support. <a href=\"https://goo.gl/maps/4tAeQV5WpaHavU9n8\">Parking</a> is limited on the A54.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.2136774,
    lng: -1.9895728,
    osgrid: "SK 007 685"
  },
  {
    id: 75,
    name: "Tor Rock",
    pin: "pin.png",
    rank: 41,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunrise",
    image: "tor-rock.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Tor Rock is a small limestone rock to the North of <a href=\"#chrome-hill\">Chrome Hill<a/>. It gives great views of the Upper Dove Valley and Chrome Hill at sunrise. Parking is not so easy. I would recommend parking up at <a href=\"https://goo.gl/maps/ntFq4DRuM1ydozcz7\">Brandside</a> and then it’s a 30 minute walk in. Defiantly best shot at sunrise.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.207989,
    lng: -1.9038248,
    osgrid: "SK 065 678"
  },
  {
    id: 76,
    name: "Trinnacle",
    pin: "pin.png",
    rank: 18,
    difficulty: 4,
    season: "Autumn",
    bestTime: "Sunset",
    image: "trinnacle.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "A darker wilder remote landscape, not to dissimilar to Kinder Scout landscapes if your more familiar with those. I visited a few years ago and keep meaning to re-visit. I parked at <a href=\"https://goo.gl/maps/UMb6MnQhfasbwwky8\">Binn Green Car Park</a>, its then a good hour walk up to the Trinnacle. I nearly walked past it as well!",
    readmore: "none",
    readmoreurl: "",
    county: "Greater Manchester",
    lat: 53.539957,
    lng: -1.9447128,
    osgrid: "SE 037 048"
  },
  {
    id: 77,
    name: "Upper Tor",
    pin: "pin.png",
    rank: 20,
    difficulty: 4,
    season: "Any",
    bestTime: "Sunrise",
    image: "upper-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "I have tried to photography Upper Tor several times. It is a small crop of weathered gritstone on the edge of Kinder Scout. You need to dedicate some time to getting up on top in time for the best light, and it is about 1hr 30min walk to get up and around Kinder to the Tor, the views back down to Hope Valley are stunning and it’s a shot that I will continue to seek. Parking is via <a href=\"https://goo.gl/maps/ZSQS3iMMHf1KZbyVA\">Edale</a> - 138 spaces and is a pay and display.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.385438,
    lng: -1.8308059,
    osgrid: "SK 113 876"
  },
  {
    id: 78,
    name: "Upper Whittle",
    pin: "pin.png",
    rank: 101,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunrise",
    image: "upper-whittle.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Upper Whitle is near the village of Longnor on the Staffordshire Peak. A classic view can be admired of the Dove Valley with Edgetop farm in the foreground and Parkhouse hill in the far distance. It’s a roadside shot so very easy and accessible. Travel from Sheen towards Longnor and you will admire the when you hit the downhill \"S\" section of the road.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.174651,
    lng: -1.8517277,
    osgrid: "SK 100 641"
  },
  {
    id: 79,
    name: "Warslow",
    pin: "pin.png",
    rank: 91,
    difficulty: 1,
    season: "Spring",
    bestTime: "Sunrise",
    image: "warslow.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "You don’t see many landscape shots from the Warslow area of the Peak but I have managed to get a few. Best shot early morning as the mist lingers in the Manifold Valley. Ecton Hill near-by is a great vantage point if you want to get up higher.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.128718,
    lng: -1.8846577,
    osgrid: "SK 078 590"
  },
  {
    id: 80,
    name: "Warslow Moor",
    pin: "pin.png",
    rank: 96,
    difficulty: 1,
    season: "Winter",
    bestTime: "Midday",
    image: "warslow-moor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Near the village of Warslow is Warslow Moor. There are some unique woods and isolated trees to create some abstract shots when the weather is right. I tend to visit here in low mist / cloud or the snow midday.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.134519,
    lng: -1.8868629,
    osgrid: "SK 076 597"
  },
  {
    id: 81,
    name: "Waterfall Swallet",
    pin: "pin.png",
    rank: 90,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "waterfall-swallet.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Between the villages of Foolow and Eyam on the unnamed road is a small wood next to the road. Within that wood is Waterfall Swallet. It’s a 30ft waterfall that cascades best after a good rainfall. Access is very limited as is the parking. I would park in either one of the villages and walk in. Take care climbing down as it can be slippy.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.2900525,
    lng: -1.705488,
    osgrid: "SK 197 770"
  },
  {
    id: 82,
    name: "Wetton Hill",
    pin: "pin.png",
    rank: 44,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunrise",
    image: "wetton-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/staffordshire-peak-district-2/\">James Pictures</a>",
    content: "Wetton Hill, above the village of Wetton in the Staffordshire Peak has views over both the Dove Valley and Manifold Valley. It’s one of the best vantage spots when a temperature inversion hits. Parking is at the village of Wetton and it’s a 30 minute walk to either vantage.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.106214,
    lng: -1.8356537,
    osgrid: "SK 111 565"
  },
  {
    id: 83,
    name: "White Tor",
    pin: "pin.png",
    rank: 82,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Sunset",
    image: "white-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "White Tor is a small outcrop of gritstone rocks on Derwent Edge close to the Salt Cellar. Best shot at sunrise as the sun hits the rocks. Parking is via <a href=\"https://goo.gl/maps/EvecDUf1u5FtV9Db7\">Heatherdene Car Park</a> and then a good hours walk up on top.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.407518,
    lng: -1.7062017,
    osgrid: "SK 196 901"
  },
  {
    id: 84,
    name: "Windgather Rocks",
    pin: "pin.png",
    rank: 34,
    difficulty: 1,
    season: "Spring",
    bestTime: "Sunset",
    image: "windgather-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/windgather-rocks/\">James Pictures</a>",
    content: "Windgather Rocks in the High Peak District are on the county border with Cheshire. It’s a gritstone crag popular with climbers and walkers. Its named after the westerly winds and is best photographed at sunset. Parking is on location as it is roadside.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3009103,
    lng: -2.0261376,
    osgrid: "SJ 983 782"
  },
  {
    id: 85,
    name: "Winnats Pass",
    pin: "red-pin.png",
    rank: 4,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunrise",
    image: "winnats-pass.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/winnats-pass-in-derbyshire/\">James Pictures</a>",
    content: "Winntas Pass is defiantly in the top 10 places to visits in the Peak for an amazing view of the Hope Valley, even better if you get to witness an inversion. Fairly easy to get to with only a 20 minute walk in. It’s a must!",
    readmore: "block",
    readmoreurl: "#winnats-pass",
    county: "Derbyshire",
    lat: 53.3401843,
    lng: -1.8027509,
    osgrid: "SK 132 826"
  },
  {
    id: 86,
    name: "Wolfscote Dale",
    pin: "pin.png",
    rank: 29,
    difficulty: 3,
    season: "Spring",
    bestTime: "Sunrise",
    image: "wolfscote-dale.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Wolfscote Dale happens to be one of my favourite dales in the Peak, for its remoteness and stunning beauty. It is on par with Winntas Pass in my opinion with its steep sided limestone rock formations, but instead of a road running through it has the River Dove. No nearby Parking im afraid, the closest is probably Beresford Dale or Milldale with a 30 minute walk in.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.113772,
    lng: -1.7993957,
    osgrid: "SK 135 574"
  },
  {
    id: 87,
    name: "Wolfscote Hill",
    pin: "pin.png",
    rank: 22,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunrise",
    image: "wolfscote-hill.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Wolfscote Hill is a limestone hill above the dale, not that easily accessible with a 40 minute walk in from Beresford Dale. The views are 360 panoramic, flat towards Derbyshire with not that much foreground interest. The best views are looking back into Staffordshire towards Wetton and Beresford Dale.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.121925,
    lng: -1.7974365,
    osgrid: "SK 136 583"
  },
  {
    id: 88,
    name: "Woolpacks",
    pin: "pin.png",
    rank: 26,
    difficulty: 4,
    season: "Any",
    bestTime: "Sunset",
    image: "woolpacks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The Woolpacks are a set of stunning gritstone rock formations on Kinder Scout that have been formed over the years by the wind and elements. The rocks are spread out over a good area so you can have a good play around at various compositions. Leave enough time so you can make use of the side light, park at <a href=\"https://goo.gl/maps/sMuK3KGG19A7KH2a8\">Barber Booth</a> and walk up Jacobs Ladder, its a 3 mile walk and marked on OS maps as Crowden Tower.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.379464,
    lng: -1.8655525,
    osgrid: "SK 090 869"
  },
  {
    id: 89,
    name: "Wyming Brook",
    pin: "pin.png",
    rank: 50,
    difficulty: 2,
    season: "Autumn",
    bestTime: "Midday",
    image: "wyming-brook.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/wyming-brook-2/\">James Pictures</a>",
    content: "Wyming Brook is a Site of Special Scientific Interest (SSSI) its a midday location where you can get some stunning shots of the water flowing down the brook. Probably best shot at Autumn. Parking is on site and you can easily spend a few hours here, its on par with Padley Gorge if you have ever been there.",
    readmore: "none",
    readmoreurl: "",
    county: "South Yorkshire",
    lat: 53.3703943,
    lng: -1.5948924,
    osgrid: "SK 270 860"
  },
  {
    id: 90,
    name: "Ashway Rocks",
    pin: "pin.png",
    rank: 11,
    difficulty: 3,
    season: "Any",
    bestTime: "Sunset",
    image: "ashway-rocks.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/peak-district-landscape-photography/ashway-rocks/\">James Pictures</a>",
    content: "Ashway Rocks in the Dark Peak are a pleasant change from the hustle and bustle of the Derbyshire Peak. Sat above Dovestones Reservoir on Saddleworth Moor you can get a great view looking back onto the reservoir. This is the location if you want remoteness. Best shot at Sunset, I park at <a href=\"https://goo.gl/maps/A73DxT61hrdqkqR57\">Bin Green Car Park</a>, its then a 40 minute walk up.",
    readmore: "none",
    readmoreurl: "",
    county: "Greater Manchester",
    lat: 53.539281,
    lng: -1.9608887,
    osgrid: "SE 026 047"
  },
  {
    id: 91,
    name: "Minninglow",
    pin: "pin.png",
    rank: 80,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunset",
    image: "minninglow.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "You can see Minninglow from a far, its a small clump of trees that have a Neolithic chambered tomb and two Bronze Age bowl barrows. Park at the Car Park on <a href=\"https://goo.gl/maps/V5CRk4F24ySDQ1GZ8\">Parwich Lane</a> and the walk in is 30 minutes or so.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.1130247,
    lng: -1.6918382,
    osgrid: "SK 207 573"
  },
  {
    id: 92,
    name: "Birchen Edge",
    pin: "pin.png",
    rank: 62,
    difficulty: 2,
    season: "Spring",
    bestTime: "Sunset",
    image: "birchen-edge.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Birchen Edge has several commemorations to Lord Nelson, a 3 metre tall gritstone column built in 1810 and 3 large ship rocks with the names of victory, defiance and royal sovereign (ships) engraved on them. You can park at the bottom with a 30 minute walk in. Best shot at sunset.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.2524283,
    lng: -1.5831578,
    osgrid: "SK 278 730"
  },
  {
    id: 93,
    name: "Black Brook",
    pin: "pin.png",
    rank: 60,
    difficulty: 1,
    season: "Autumn",
    bestTime: "Sunset",
    image: "black-brook.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Black Brook is between Roach End Barn and Gradbach wood at the Northern end of the Roaches it has great views over to Cheshire's Shutlingsloe and is covered in purple heather when in flower. It's a roadside location and is best shot at Sunset. Parking is roadside.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.17755,
    lng: -2.0051137,
    osgrid: "SJ 997 644"
  },
  {
    id: 94,
    name: "Magpie Mine",
    pin: "pin.png",
    rank: 81,
    difficulty: 1,
    season: "Spring",
    bestTime: "Sunset",
    image: "magpie-mine.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Magpie Mine is a former lead mine near Sheldon and is an industrial heritage site you can check out <a href=\"https://pdmhs.co.uk/magpie-mine-peak-district/\">Peak District Mines Historical Society</a> for its history. I very accessible with parking just of the main road. The best shots I have seen from here were taken at Spring as the flowers emerge and astrophotography shots with the Milky Way in the background, and the chimney in the foreground.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.210378,
    lng: -1.7432603,
    osgrid: "SK 172 681"
  },
  {
    id: 95,
    name: "Middle Black Clough",
    pin: "pin.png",
    rank: 15,
    difficulty: 3,
    season: "Spring",
    bestTime: "Midday",
    image: "middle-black-clough.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Middle Black Clough is a stunning waterfall in a stunning location. The best waterfall in the Peak District! Parking of the A628 it’s a good mile walk up Black Clough heading for the middle waterfall of three streams. Following the path, you cross the stream from right to left and continue up the winding path following the left flow of water. Once you have found it admire! Be careful underfoot as its very slippery.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.4876306,
    lng: -1.826359,
    osgrid: "SK 116 990"
  },
  {
    id: 96,
    name: "Ashopton Viaduct",
    pin: "pin.png",
    rank: 79,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "ashopton-viaduct.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Ashopton Viaduct is on the Snake Pass road over Ladybower Reservoir. Parking is a little harder now since the addition of double yellow lines everywhere. It is a cracking spot to have a go at long exposures. Can be shot at any time of the day, however I have seen the better shots at sunrise. There is only 1 accessible side to photograph which is the side leading to Fairhomes Visitors Centre.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.3746522,
    lng: -1.7133588,
    osgrid: "SK 191 864"
  },
  {
    id: 97,
    name: "Fairbrook Waterfall",
    pin: "pin.png",
    rank: 49,
    difficulty: 3,
    season: "Autumn",
    bestTime: "Midday",
    image: "fairbrook-waterfall.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "The waterfall at Fairbrook is another beautiful scene to photograph. Best shot in Autumn when the heather is in bloom. It’s a 30 minute walk from the roadside parking on the A57 Snake Pass up Fairbrook. I have given this location a 3 star because once on location it is an awkward climb down to the waterside. Please take your time and tell others as a <a href=\"https://www.derbytelegraph.co.uk/news/local-news/man-falls-death-visiting-secluded-1019297\">man fell and died</a> in 2018 here.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.405822,
    lng: -1.8369721,
    osgrid: "SK 109 899"
  },
  {
    id: 98,
    name: "Robin Hoods Stride",
    pin: "pin.png",
    rank: 65,
    difficulty: 1,
    season: "Any",
    bestTime: "Sunset",
    image: "robin-hoods-stride.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Robins Hood's Stride is a gritstone rock formation that Robin Hood supposedly strode between the two pillars that are 20 metres apart! Aside from that it has been heavily defaced over the years with engravings but is a nice quite location to admire a sunset. Best shot at sunset. Parking is roadside or at <a href=\"https://goo.gl/maps/1w3Kt2JxpW54euPaA\">Cratcliffe Car Park</a>.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.1569568,
    lng: -1.6681716,
    osgrid: "SK 222 622"
  },
  {
    id: 99,
    name: "Whinstone Lee Tor",
    pin: "pin.png",
    rank: 37,
    difficulty: 2,
    season: "Any",
    bestTime: "Sunset",
    image: "whinstone-lee-tor.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Whinstone Lee Tor is a gritstone rock formation overlooking Ladybower Reservoir. Its views of Ashopton Viaduct and Win Hill are best captured at sunset to take advantage of the side light on the rocks. It’s a 30 minute (ish) uphill walk from either Heatherdene or Cutthroat Bridge Car Parks.",
    readmore: "none",
    readmoreurl: "",
    county: "Derbyshire",
    lat: 53.384502,
    lng: -1.703394,
    osgrid: "SK 198 875"
  },
  {
    id: 100,
    name: "Luds Church",
    pin: "pin.png",
    rank: 71,
    difficulty: 1,
    season: "Any",
    bestTime: "Midday",
    image: "luds-church.jpg",
    imagecredit: "Image &copy; <a target=\"_blank\" href=\"https://www.jamespictures.co.uk/\">James Pictures</a>",
    content: "Luds church is a Roaches gritstone chasm in Back Forest nearby Roach End Barn in the Staffordshire Peak. It is not so photogenic, so ranks near the bottom but I should imagine many Instagram type individuals would love it here for the atmosphere. Best shot in the midday and parking is at Roach End Barn. It’s only a 30 minute walk in from the car.",
    readmore: "none",
    readmoreurl: "",
    county: "Staffordshire",
    lat: 53.1877513,
    lng: -2.0207619,
    osgrid: "SJ 987 656"
  }
]
